### ISSUE TITLE
Adding new policies to existing roles fail

### ISSUE THREAD

**Issue by phalasz** [kaliop-uk/ezmigrationbundle#10]
On eZ Platform adding new policies to existing roles fail with the following error message:

`Error "Argument 'module' is invalid: 'NULL' is wrong value in class 'PolicyCreateStruct'"`

```
-
  mode: update
  type: role
  name: Editor
  policies:
    add:
      -
        module: content
        function: create
        limitation:
          -
            type: ParentClass
            value: [1, 42]
          -
            type: Class
            value: [reference:contentTypeId1, reference:contentTypeId2, reference:contentTypeId3]
```
