### ISSUE TITLE
netgen/tagsbundle subTreeLimit migration aborted

### ISSUE THREAD

**Issue by volarname** [kaliop-uk/ezmigrationbundle#109]
when using "netgen/tagsbundle": "3.0.0-rc1"
the following migration
```
-
    mode: update
    type: content_type
    lang: slk-SK
    identifier: article
    attributes:
        -
            identifier: keywords
            type: eztags
            validator-configuration:
                TagsValueValidator: { subTreeLimit: 2 }
```

will fail with error:

```
Processing 20170303111827_content_type_update-article-keywords-internal-tags.yml

Migration aborted! Reason: Error in execution of step 1: ContentType FieldDefinitions did not validate
Setting "%setting%" is unknown - array (
  '%setting%' => 'subTreeLimit',
)
Setting "%setting%" is unknown - array (
  '%setting%' => 'maxTags',
) in file /app/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Repository/Helper/ContentTypeDomainMapper.php line 285
```

**Comment by gggeek** [comment]
Hello.

I tried to reproduce this, but I am at a loss for the moment:
- installed ezplatform 1.8
- installed eztagsbundle 3.0
- tried to create a content type with a tags field using a migration, and I get the error `value must be an existing tag ID`
- but I can not find any panel in the admin interface to manage the tags, as was possible in eZ5 ?

**Comment by gggeek** [comment]
ps: I managed to reset the admin interface.
But I still cant reproduce the error.

These are the 2 migrations I executed:
```
-
    mode: create
    type: content_type
    content_type_group: Content
    name_pattern: '<title>'
    identifier: testcontent
    name: TestContent
    attributes:
        -
            identifier: title
            type: ezstring
        -
            identifier: keywords
            type: eztags

-
    mode: update
    type: content_type
    match:
        identifier: testcontent
    attributes:
        -
            identifier: keywords
            type: eztags
            validator-configuration:
                TagsValueValidator: { subTreeLimit: 1 }
```
