### ISSUE TITLE
Associative array in ezselection options

### ISSUE THREAD

**Issue by Saimount** [kaliop-uk/ezmigrationbundle#124]
I added associative array in ezselection options : 
```
-
    mode: create
    type: content_type
    identifier: content_type_test
    attributes:
        -
            type: ezselection
            identifier: align
            field-settings:
                isMultiple: false
                options:
                    center: "Center position"
                    left: "Left position"
                    right: "Right position"
```
Everything seems to be ok, content type is created with specified attributes. But when I want to modify this content type on another attributes : 
```
-
    mode: update
    type: content_type
    identifier: content_type_test
    attributes:
        -
            type: ezstring
            identifier: title
```
During migration, eZPublish creates a draft of content type. Then, the `SelectionConverter` class is casting options key as integer. (see https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/SelectionConverter.php#L111 for details)
After migration, ezselection attribute has following options : 
```
[0 => "Right position"]
```
I know that ezselection doesn't natively supports associative keys, but there are no warnings when trying to use this "feature", and everything seems to be ok after first migration.
