### ISSUE TITLE
Cannot set mime_type on file upload

### ISSUE THREAD

**Issue by franck-grenier** [kaliop-uk/ezmigrationbundle#147]
Hello Kaliop,
we are uploading css files into ezbinaryfile attributes during a migration. Though we explicitly set the mime type with `mime_type: text/css` in the migration file, EZ (5.4.10) saves `text/plain` mime type.

We are doing that kind of migration : 

```
-
    type: content
    mode: update
    match:
        content_id: 31499
    lang: fre-FR
    attributes:
        css:
            path: 'css/css_31499.css'
            mime_type: 'text/css'
```

Do you have any feedback on this bug ?

Thanks
