### ISSUE TITLE
Possibility to update multiple content types?

### ISSUE THREAD

**Issue by dantleech** [kaliop-uk/ezmigrationbundle#154]
Is it / could it be possible to update multiple content types?
```
-
    identifier: [ article, post, comment ]
    mode: update
    type: content_type
    attributes:
      -
        type: ezobjectrelation
        name: newfield
        identifier: newfield
        required: false
```

**Comment by gggeek** [comment]
No reason why this would not work...
Did you try to use the `match` keyword to select the content types to operate on? the `identifier` keyword has been deprecated for a while and does not have the same flexibility

**Comment by dantleech** [comment]
Tried:

```

**Comment by dantleech** [comment]
Tried:

```yaml
-
    mode: update
    type: content_type
    match:
        or:
            - { identifier: comment }
            - { identifier: standard_article }
            - { identifier: alpha_article }
            - { identifier: tip_article }
            - { identifier: guide }
            - { identifier: multimedia }
            - { identifier: paid_post_article }
```

and get:

```
Migration aborted! Reason: Error in execution of step 1: The identifier of a content type is required in order to update it. in file /app/vendor/kaliop/ezmigrationbundle/Core/Executor/ContentTypeManager.php line 85
```

But - it looks like we are using a fork based on `2.5.1` - guessing that this is not supported in that version?
