### ISSUE TITLE
Error when migrating ezrichtext field

### ISSUE THREAD

**Issue by magarzon** [kaliop-uk/ezmigrationbundle#160]
Hi.

I have a field in one of my content types that is of RichText type.

In the yaml generated by the command kaliop:migration:generate, that field has the value of the field inside an "xml" field, but when I execute the kalop:migration:migrate, this code:

https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Core/FieldHandler/EzRichText.php#L34

is trying to access the RichText content in the "content" field instead the xml one.

Here is a snippet of the generated yaml:

```
attributes:
        reference: terms_and_conditions
        content:
            xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>...."
```
