### ISSUE TITLE
Generating migration in specified language is not working

### ISSUE THREAD

**Issue by damianz5** [kaliop-uk/ezmigrationbundle#166]
[Ezplatform demo] - after adding a new language to blog_post, I've tried to generate a migration using command:
```
bin/console kaliop:migration:generate --format=yml --type=content --match-type=content_type --match-value=blog_post --mode=create --lang=fre-FR
```
the result file was generated with proper `    lang: fre-FR` but attributes was empty 
`attributes: {  }`     

workaround is to replace this line https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Core/Matcher/ContentMatcher.php#L101

with:
```
$results = $this->repository->getSearchService()->findContent($query, ['languages' => ['fre-FR']]);
```

the language code parameter (`--lang=`) should be passed to findContent method

**Comment by gggeek** [comment]
Seems weird... the correct language used to serialize the attributes is used in https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Core/Executor/ContentManager.php#L559

I will investigate a bit more

**Comment by gggeek** [comment]
Tested with ezplatform 210:

- created test content type 'tesct', in english. Fields: title (string), tags (eztags)
- added new language: french (fre-FR)
- created a 'testct' content in english
- added for it a french translation
- executed `php bin/console ka:mig:gen AppBundle --format=yml --type=content --match-type=content_type --match-value=testct --mode=create --lang=fre-FR`

got correct results:
```yaml
-
    type: content
    mode: create
    content_type: testct
    parent_location: 2
    priority: 0
    is_hidden: false
    sort_field: name
    sort_order: ASC
    remote_id: 73cdfd20849fad9786bdfeaa988a50ce
    location_remote_id: 7773bd50d64fe204a6aa463ca1d93df1
    lang: fre-FR
    section: 1
    owner: 14
    modification_date: 1532131229
    publication_date: 1532131132
    always_available: false
    attributes:
        title: 'Test (french)'
        tags: {  }
```

**Comment by gggeek** [comment]
Same when I created a content directly in french:

```yaml
-
    type: content
    mode: create
    content_type: testct
    parent_location: 2
    priority: 0
    is_hidden: false
    sort_field: name
    sort_order: ASC
    remote_id: 175fc559bcf0ba5abea16b126d554acf
    location_remote_id: 41129a0ea2ad97183749d880f5b6c100
    lang: fre-FR
    section: 1
    owner: 14
    modification_date: 1532131898
    publication_date: 1532131898
    always_available: false
    attributes:
        title: 'Test2 (french only)'
        tags: {  }
```
