### ISSUE TITLE
Update of content_type_group not supported

### ISSUE THREAD

**Issue by vfaisse** [kaliop-uk/ezmigrationbundle#170]
The key "content_type_group" for an update of a content_type don't assign the class to the specified content type group.

**Comment by gggeek** [comment]
True. This is not yet supported (not documented), but it is doable, as we have the `assignContentTypeGroup` call available.

The interesting part would be: since a ContentType can be part of many groups, how do we manage both adding it to a new groups and removing it from a group it already belongs to? Do we do like we do for allowing both adding & removing of attributes?

**Comment by gggeek** [comment]
ps: while at it: it would also make sense to allow to assign the class to many groups in the creation step

**Comment by gggeek** [comment]
Implemented in 5.3

**Comment by blankse** [comment]
@gggeek It seems the `content_type_group` option doesn't work. 
e. g.
```
-
    type: content_type
    mode: update
    content_type_group: 'New Group'
    match:
        or:
            - { contenttype_identifier: content_type1 }
            - { contenttype_identifier: content_type2 }
```
The setContentTypeGroup method set the new group correct:
https://github.com/kaliop-uk/ezmigrationbundle/blob/4fd5be1056a1d073279808b60a778cb3e70f24fa/Core/Executor/ContentTypeManager.php#L205

But the publishContentTypeDraft removed it:
https://github.com/kaliop-uk/ezmigrationbundle/blob/4fd5be1056a1d073279808b60a778cb3e70f24fa/Core/Executor/ContentTypeManager.php#L288
