### ISSUE TITLE
User Create extra attributes

### ISSUE THREAD

**Issue by raupie** [kaliop-uk/ezmigrationbundle#191]
I added an extra attribute to the user content_type for storing a users 'job title'.

However, when creating a new user using the `type: user` it is unable to match the `job_title` attribute so it ends up null. 

I suppose the other way to do this is to create the user via the 
```
type: content
mode: create
content_type: user
...
```

**Comment by raupie** [comment]
Looks like I can do something like this as a work around.

```
-
  type: user
  mode: create
  first_name: Stephen
  last_name: King
  username: stephen.king
  email: stephen.king@author.com
  password: password123
  lang: eng-GB
  groups: [authors_group]
  references:
    -
      identifier: ref.user.stephen_king
      attribute: user_id

-
  type: content
  mode: update
  lang: eng-GB
  match:
    content_id: "reference:ref.user.stephen_king"
  new_remote_id: user.stephen_king
  attributes:
    job_title: 'Famous Author'
```
