### ISSUE TITLE
improve eZ Migration Bundle compatibility with Doctrine Migrations Bundle

### ISSUE THREAD

**Issue by SalvatorePollaci** [kaliop-uk/ezmigrationbundle#193]
It seems that eZ Migration Bundle is not compatible with Doctrine Migrations Bundle. 

**Scenario 1 - Doctrine Standard Config**
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: '%database_driver%'
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
                schema_filter: ~^(?!ez)~
```
When I run:
```
bin/console doctrine:migrations:diff 
```
the generated migration file tries to DROP and CREATE the 'kaliop_migrations' table.

**Scenario 2 - Filter out kaliop_migrations in schema_filter doctrine config option**
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: '%database_driver%'
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
                schema_filter: ~^(?!ez|kaliop_migrations)~
```
Whatever ez migration bundle command I run, for example:
```
bin/console kaliop:migration:status
```

I get the following error message:
```
In ConnectionHandler.php line 366:

  An exception occurred while executing 'CREATE TABLE kaliop_migrations (migration VARCHAR(255) NOT NULL, path VARCHAR(4000) NOT NULL, md5 VARCHAR(32) NOT NULL, execution_date INT DEFAULT NULL, status INT NOT NULL, execution_error VARCHAR(4000) DEFAULT NULL, PRIMARY KE
  Y(migration)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kaliop_migrations' already exists


In AbstractMySQLDriver.php line 58:

  An exception occurred while executing 'CREATE TABLE kaliop_migrations (migration VARCHAR(255) NOT NULL, path VARCHAR(4000) NOT NULL, md5 VARCHAR(32) NOT NULL, execution_date INT DEFAULT NULL, status INT NOT NULL, execution_error VARCHAR(4000) DEFAULT NULL, PRIMARY KE
  Y(migration)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kaliop_migrations' already exists


In PDOConnection.php line 62:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kaliop_migrations' already exists


In PDOConnection.php line 60:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kaliop_migrations' already exists


kaliop:migration:status [--path [PATH]] [--summary] [--todo] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--siteaccess [SITEACCESS]] [--] <command>
```
