### ISSUE TITLE
RoleManager::createLimitation fails when using array reference

### ISSUE THREAD

**Issue by jdegrange** [kaliop-uk/ezmigrationbundle#202]
When setting a custom reference, referencing an array symfony parameter, I want to use this reference as values for a limitation when creating a new Role.
But this fail because the array is being encapsulated in an other array.
This array :
````
array(2) {
   [0] =>
   string(6) "value1"
   [1] =>
   string(6) "value2"
 }
````
give this : 
````
array(1) {
 [0] =>
 array(2) {
   [0] =>
   string(6) "value1"
   [1] =>
   string(6) "value2"
 }
}
````

Here is a migration sample to reproduce the problem : 
````
-
  type: reference
  mode: set
  identifier: front_siteaccess
  value: '%ezpublish.siteaccess.groups.instance_front_group%'  # => has to be an array
-
  type: reference
  mode: dump
  identifier: reference:front_siteaccess 
-
  type: role
  mode: create
  name: AnonymeTest
  policies:
  -
    module: user
    function: login
    limitations:
      - { identifier: SiteAccess, values: "reference:front_siteaccess" }  # => using my array here fail
````
Thank you
