### ISSUE TITLE
Cannot update content field `always_available`

### ISSUE THREAD

**Issue by TFohrer** [kaliop-uk/ezmigrationbundle#209]
When trying to update the availability of a content item like this e.g.: 

```
-
    type: content
    mode: update
    match:
        content_type_identifier: ['folder']
    always_available: false 
```

I'm always getting this error: 

`Migration failed! Reason: Error in execution of step 15: Missing values in file /var/www/html/project/ezplatform/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Persistence/Doctrine/UpdateDoctrineQuery.php line 112
`

Using version 5.9.4 of ezmigrationbundle and ezplatform version 2.4.1

**Comment by TFohrer** [comment]
Works when I add another field like 'modification_date'. So this updated statement works: 

```
 -
    type: content
    mode: update
    match:
        content_type_identifier: ['folder']
    modification_date: 1553253910
    always_available: false 
```
