### ISSUE TITLE
Add support for ezmatrix field: defining columns in Content Type Migration and filling columns in Content Migration

### ISSUE THREAD

**Issue by maczuk** [kaliop-uk/ezmigrationbundle#217]
Add support for defining columns for example:

Content Type Migration:
```
-
    type: content_type
    mode: create
    content_type_group: 1
    name: Article
    identifier: article
    name_pattern: <title>
    is_container: false
    attributes:
    	-
            type: ezstring
            name: Title
            identifier: title
            required: true
            searchable: true
        -
            type: ezmatrix
            name: Bibliography
            identifier: bibliography
            columns:
                - { name: Autors, identifier: authors }
                - { name: Title, identifier: title }
                - { name: Release information, identifier: release_info }
```

Content Item Migration:
```
-
    type: content
    mode: create
    content_type: reference:content_type_journal_article
    parent_location: reference:journal_issue_52019_loc
    owner: admin
    attributes:
        title: Sample
        bibliography:
            -
                authors: 'Author A, Author B'
                title: 'Lorem ipsum'
                release_info: 'Cracov 2012'
            -
                authors: 'Author 1, Author 2'
                title: 'Lorem ipsum dolor sit amet'
                release_info: 'R info abc'
            -
                authors: 'Athor I, Author II'
                title: 'This is a title'
                release_info: 'Warsaw 2000'
```

Thanks!
