### ISSUE TITLE
Content update with `and` and `attribute`

### ISSUE THREAD

**Issue by Codein-Alex** [kaliop-uk/ezmigrationbundle#223]
I have the following update statement.

```
-
    type: content
    mode: update
    match:
        and:
            -
                location_id: 167
            -
                content_type_identifier: plan
            -
                attribute:
                    name:
                        eq: Alex
    attributes:
        tag: Alex
```

Says `content  has been updated`.

But it does not.

If I remove `attribute` part. 

```
            -
                attribute:
                    name:
                        eq: Alex
```

*It does work!* `content 'Alex' has been updated`

My name field is an `ezstring`.

```
Nom | name | ezstring
```

I noticed that when it says that content has been updated, name does not appear like KM did not find any content.

What is wrong with the statement?

```
versions : * 5.10.1
```

**Comment by gggeek** [comment]
Sorry for taking so long to respond.

I think that the problem might come from the fact that you are not running the migration with the correct language setting (and have not set up fre-FR as the default content language for your db).

Here is a simple test migration that does work on my setups, which looks exactly your scenario:

```
-
    type: content
    mode: load
    match:
        and:
            -
                location_id: 51
            -
                content_type_identifier: folder
            -
                attribute:
                    name:
                        eq: Images
    #expect: one
    references:
        -   identifier: matched
            attribute: count
        -   identifier: ct
            attribute: content_type_identifier

-
    type: reference
    mode: dump
    identifier: reference:matched
-
    type: reference
    mode: dump
    identifier: reference:ct
```
