### ISSUE TITLE
Unable to delete all contents of content types

### ISSUE THREAD

**Issue by SalvatorePollaci** [kaliop-uk/ezmigrationbundle#227]
Hi I'm trying to delete all contents of a list of content types as so:

```
-
    type: content
    mode: delete
    match:
        content_type_identifier: [product, product_accessory]
```

But the migration fails with the following error message:

```
Migration failed! Reason: Error in execution of step 3: Intentionally not implemented: No visitor available for: eZ\Publish\API\Repository\Values\Content\Query\SortClause\LocationDepth in file /application/vendor/ezsystems/ezplatform-solr-search-engine/lib/Query/Common/SortClauseVisitor/Aggregate.php line 80
```

Is this a bug? Am I forgetting do to something?
