### ISSUE TITLE
Unable to modify content_types in version 2.0.0-beta7

### ISSUE THREAD

**Issue by seiji-okamoto-informa** [kaliop-uk/ezmigrationbundle#50]
When attempting to update a content_type via the yml definition, I get the following error:

> Migration aborted! Reason: Error in execution of step 1: Could not find 'eZ\Publish\SPI\Persistence\Content\Type' with identifier 'ID: featured_banner, Status: 0' in file /srv/www/www.ovumkc.com/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php line 251

The migration is attempting to update the identifier for the content_type itself, along with several attributes.  The migration definition is as follows:

```yml
-
    mode: update
    type: content_type
    identifier: featured_banner
    new_identifier: front_page_banner
    attributes:
        -
            identifier: featured_banner_title
            new_identifier: title
            name: Title
        -
            identifier: featured_banner_image
            new_identifier: background_image
            name: Background Image
            description: Image used for background of the banner
```
