### ISSUE TITLE
SiteAcces Policy not working

### ISSUE THREAD

**Issue by mozzymoz** [kaliop-uk/ezmigrationbundle#80]
Hi there, 
I am trying to set the user:login SiteAccess policy in migrations like so

``` yaml
- type: role
  mode: update
  match:
    id: 1
  policies:
  - module: user
    function: login
    limitations:
    - identifier: SiteAccess
      values: ['site', 'kfb2c']
```

For some reason it is not working and no errors are given.

**Comment by gggeek** [comment]
Mmm, nothing comes to my mind, will try to reproduce. Are you using version 2 ?

**Comment by mozzymoz** [comment]
That would be version 2.4.1, I just tried it again with a fresh install, added a new siteaccess configuration, generated the migration and ran it. No luck unforutnately

**Comment by gggeek** [comment]
I just tested the following:
- ezp 5.4
- ezmigrations 3.0-beta4
- create new role, without policies (role 21)
- generate migration, edit it, run it:

```
-
    mode: update
    type: role
    match:
        id: 21
    policies:
        -
            module: user
            function: login
            limitations:
                - { identifier: SiteAccess, values: [abc, abc_usa] }
```

And it does work.

I think that there might be 2 factors at play in your case:
1. the 'match' keyword for roles is only supported starting at version 3 of migration bundle. For v2, the only allowed syntax is to match roles using 'name' as top-level key
2. there were a couple of places in the code where errors in role assignments would ignore not-found entities without a warning. This has also been fixed in version 3 to throw exceptions
